### ISSUE TITLE
Option to turn off log prefixes

### ISSUE THREAD

**Issue by illarionvk** [DarthSim/hivemind#10]
My Heroku app processes [emit logs in JSON format](https://getpino.io/) to be ingested by LogDNA parser. I'm currently using [Honcho](https://honcho.readthedocs.io/en/latest/using_procfiles.html#using-honcho) (Python port of Foreman) with `--no-prefix` option to ensure the logs are parsed correctly.

Is there any way to turn off log prefixes in hivemind?

**Comment by DarthSim** [comment]
Added to [v1.0.5](https://github.com/DarthSim/hivemind/releases/tag/v1.0.5). Thanks to @ppressives
