### ISSUE TITLE
Error installing Hivemind with Go 1.13

### ISSUE THREAD

**Issue by look** [DarthSim/hivemind#15]
Running `go get github.com/DarthSim/hivemind@v1.0.6` I got the following error:

```
build github.com/DarthSim/hivemind: cannot load gopkg.in/urfave/cli.v1: cannot find module providing package gopkg.in/urfave/cli.v1
```

I [found a similar bug report](https://github.com/mozilla/sops/issues/515) and worked around it with `replace gopkg.in/urfave/cli.v1 => github.com/urfave/cli v1.19.1` (the same version used in hivemind's go.mod).

https://github.com/DarthSim/hivemind/blob/f67556693e716db78ad03c034bdd340eaad0645c/go.mod#L9

**Comment by DarthSim** [comment]
Hi,
I've replaced it with the version from GitHub, it should work now

**Comment by look** [comment]
Thank you for the fix!
