### ISSUE TITLE
Make logging of timestamps optional

### ISSUE THREAD

**Issue by rkrzr** [DarthSim/hivemind#19]
> Tools can also add vanity information (unneeded timestamps in logs).

Timestamps are not just vanity information, but can add vital context if you want to know *when* something was logged. As one of my colleagues put it:

> Yeah I have great experiences with Hivemind but I must admit that I sometimes re-run tasks because I can't tell if they ran just now or an hour ago

I think making logging an optional feature would make `hivemind` *strictly better* than `foreman`, since it already is superior in terms of logging and killing processes correctly.

It would be great if you would consider adding this as a feature.

**Comment by DarthSim** [comment]
Hey @rkrzr!
Sorry for a such big delay. Added `--print-timestamps, -T` flag to v1.1.0
