### ISSUE TITLE
Add vendoring workflow to README.md

### ISSUE THREAD

**Issue by wrouesnel** [DarthSim/hivemind#2]
Currently there's no vendoring workflow noted in the README.md

At a best guess the `gvt` tool seems compatible, but `gvm` is mentioned in the commit logs.

Could this be clarified?

**Comment by turtlemonvh** [comment]
From [the travis.yml](https://github.com/DarthSim/hivemind/blob/master/.travis.yml), it looks like the project is using go modules now

**Comment by DarthSim** [comment]
Yup, I use Go modules for Hivemind now
