### ISSUE TITLE
Go module release

### ISSUE THREAD

**Issue by roopakv** [DarthSim/hivemind#21]
This tool is installable via brew. in order to maintain go 1.17 support please release a new version with go modules.

Homebrew/homebrew-core#47627

**Comment by DarthSim** [comment]
Hey Roopak!

What do you mean? Hivemind supports go modules for a long time.

**Comment by roopakv** [comment]
The last release was on Feb 15 2019, v1.0.. Go modules was added on Apr 2019. 

So could we cut a new release :)

**Comment by DarthSim** [comment]
Released a new version and bumped brew formula :)
