### ISSUE TITLE
hivemind hangs when handling more than 65536 bytes of output

### ISSUE THREAD

**Issue by cainlevy** [DarthSim/hivemind#23]
Hivemind hangs when it gets more than 65536 bytes of output from the child process. The following procfile demonstrates the problem:

```
works: hexdump -v -n 32768 -e '1/1 "%02x"' /dev/urandom
hangs: hexdump -v -n 32769 -e '1/1 "%02x"' /dev/urandom
```

I'm on MacOS 10.15 Catalina.

**Comment by DarthSim** [comment]
Hey @cainlevy!
Sorry for a such big delay. The issue is fixed in v1.1.0
