### ISSUE TITLE
Add command line argument to set window title

### ISSUE THREAD

**Issue by arrowcircle** [DarthSim/hivemind#4]
Hi!
I have 4 tabs running hivemind in my terminal and its impossible to identify what is where.
It will be nice to have the ability to set terminal title with command line (`--title` for example).
If --title argument is missing, get current directory name and put it in terminal title like `project | hivemind`.

**Comment by DarthSim** [comment]
Hey! Thanks for the feature request. The feature was added both to hivemind and overmind. Please check out the latest releases.
