### ISSUE TITLE
Using hive mind with overseer

### ISSUE THREAD

**Issue by joeblew99** [DarthSim/hivemind#6]
https://github.com/jpillora/overseer

Overseer can run a process but also upgrade it by polling to an external server for new binaries. In so doing it does not drop connections because of its forking style. You read about this on the main page.

Hivemend seems to more of a process manager and so it seems that the two can be combined together really nicely.

You should not to change either library.

Raising this for discussion as I have tried this out and it seems to work.
Have not tried with overmind / tmux yet.

**Comment by DarthSim** [comment]
As far as I understand, overseer is more about forking the main process. I don't think hivemind needs this feature because there are no frequent critical releases that are needed to be downloaded asap. And maintaining a server for hivemind binaries doesn't sound good to me.
