### ISSUE TITLE
hivemind takes 99% CPU 

### ISSUE THREAD

**Issue by alexfedoseev** [DarthSim/hivemind#7]
Hey, I noticed that hivemind takes 99% CPU all the time.
Initially, I thought it's something w/ my processes, but nope.

Procfile

```
fake: sleep 10000
```

results in

<img width="626" alt="screen shot 2017-11-09 at 12 00 48" src="https://user-images.githubusercontent.com/4244251/32588588-b62a009e-c54a-11e7-8513-af4a786b9a44.png">

Same when I run my app.

macOS: `10.12.6`
Processor: `2,9 GHz Intel Core i7`
Memory: `16 GB 2133 MHz LPDDR3`

**Comment by sheerun** [comment]
Same issue.

Here's sample of this process:
https://gist.github.com/sheerun/fddaad04ee2138ed5c5ad765c31efe3e

And here's proof it does a ton of syscalls and context switches:
https://i.imgur.com/HfTAxeT.png

**Comment by DarthSim** [comment]
Hi guys. Thanks for pointing on this. I had the same issue with overmind, but didn't checked hivemind.
Fixed in the latest release https://github.com/DarthSim/hivemind/releases/tag/v1.0.4
PR to Homebrew is waiting for merge https://github.com/Homebrew/homebrew-core/pull/20881
