### ISSUE TITLE
use PORT= in .env

### ISSUE THREAD

**Issue by zarqman** [DarthSim/hivemind#9]
It appears that hivemind 1.0.4 always sets its own value for PORT, even if PORT=1234 is present in .env.

Would it be possible for hivemind to set PORT only if PORT is not already set? Changing this would also make this compatible with foreman's behavior on this particular matter (that is, it allows PORT to be configured via .env).

**Comment by DarthSim** [comment]
Added to [v1.0.5](https://github.com/DarthSim/hivemind/releases/tag/v1.0.5).

**Comment by konsti** [comment]
This issue still exists in v1.0.6. A value for `PORT` in `.env` is totally ignored.
